[package]
name = "day_15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
indoc = "2.0.4"
regex = "1.10.3"
paste = "1.0.14"

